spring.application.name=apicrud

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:3636/qlisanpham
spring.datasource.username=postgres
spring.datasource.password=vukhanh2411

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
